name: ci

on:
  push:
    branches: ["*"]
    tags: ["*"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install
        uses: NullVoxPopuli/action-setup-pnpm@v2
        with:
          node-version: 18
          pnpm-version: 8
      - name: Build
        run: |
          pnpm run build
      - uses: actions/upload-artifact@v3
        with:
          name: releases
          path: dist/

  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.event.ref, 'refs/tags/')
    permissions:
      contents: write

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: releases
          path: dist/
      - name: Publish to github release
        uses: ncipollo/release-action@v1.12.0
        with:
          allowUpdates: true
          artifacts: dist/*
          prerelease: ${{ contains(github.event.ref, '-') }}
          replacesArtifacts: true
